apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7hfu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0065-tenant/tkwch-fix-0075-0065-app/devfile-sample-7hfu@sha256:3ffb0bd32ccb223ef66e929e30a34b7d2d0dc1280f223c1119ff1494afeb56f0
        name: my-nodejs
        resources: {}
status: {}
